version: '3.4'
services:
  run_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.8-slim-buster"
    volumes:
      - "./volume:/var/lib/data/volume"
    expose:
      - "8000"
    ports:
      - "8001:8000"
