version: "3.9"
services:
  # elastic-server service
  elastic-server:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - elastic

  # run server service
  run_server:
    container_name: run_server
    build:
      context: ./run_server
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: "3.8-slim-buster"
    volumes:
      - "./run_server/volume:/var/lib/data/volume"
    ports:
      - 8001:8000

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge
